welcome_text = "приветствие"
employ_or_employer = "Выберите работодатель вы или работник"
employ_warn_info = "as"

fill_employer = "as"
fill_job = "as"
fill_salary = "as"
fill_minage = "as"
fill_minexp = "as"
fill_date = "as"
fill_short_dsp = "as"
fill_long_dsp = "as"
save_vacancy = "as"